# Local development stack for Knowledge Commons Works
#
# Usage::
#
#   $ docker-compose up --file docker-compose.dev.yml -d
#
# Following services are included:
# - Frontend: Nginx (exposed ports: 80 and 443)
# - UI application: UWSGI (not exposed)
# - API application: UWSGI (not exposed)
# - Message queue: RabbitMQ (exposed ports: 5672, 15672)
# - pgAdmin:
#
# The following services are disabled because the
# staging instance uses AWS services
# - Cache: Redis (exposed port: 6379)
# - DB: (PostgresSQL) (exposed port: 5432 or 3306)
# - Search platform: (OpenSearch) (exposed ports: 9200, 9300)
# - OpenSearch Dashboard (view OS indexes) (exposed ports: 5601)
#
version: "2.2"
services:
  # cache:
  #   extends:
  #     file: docker-services.yml
  #     service: cache
  #   volumes:
  #     - cache_data:/data
  mq:
    extends:
      file: docker-services.yml
      service: mq
    volumes:
      - mq_data:/var/lib/rabbitmq
  # INGRESS
  frontend:
    extends:
      file: docker-services.yml
      service: frontend
    container_name: kcworks-frontend
    image: ${KCWORKS_FRONTEND_IMAGE}
    volumes:
      - static_data:/opt/static_data
    depends_on:
      - web-ui
      - web-api
    ports:
      - "80:80"

  # UI Application
  # This container holds Python, pip, the virtualenv, and the invenio code,
  # Node.js, NPM and some standard libraries Invenio usually needs
  # command: ["uwsgi /opt/invenio/var/instance/uwsgi_ui.ini --daemonize=logs/uwsgi-ui.log --log-reopen --pidfile=/tmp/kcr_ui.pid"]
  web-init:
    extends:
      file: docker-services.yml
      service: app
    image: ${KCWORKS_IMAGE}
    restart: no
    command: ["cp -r /opt/invenio/var/instance/static/. /opt/static_data/"]
    volumes:
      - static_data:/opt/static_data
  web-ui:
    extends:
      file: docker-services.yml
      service: app
    container_name: kcworks-ui
    image: ${KCWORKS_IMAGE}
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_ui.ini"]
    ports:
      - "5000"
    environment:
      - FLASK_DEBUG=1
      - INVENIO_LOGGING_CONSOLE=True
      - INVENIO_LOGGING_CONSOLE_LEVEL=DEBUG
      - INVENIO_LOGGING_FS_LEVEL=DEBUG
      - INVENIO_LOGGING_FS_BACKUP_COUNT=10
      - INVENIO_LOGGING_FS_LOGFILE=/opt/invenio/src/logs/invenio.log
    volumes:
      - archived_data:/opt/invenio/var/instance/archive
      - uploaded_data:/opt/invenio/var/instance/data
      - /${MIGRATION_LOCAL_DATA_DIR}:${MIGRATION_SERVER_DATA_DIR}

  # API Rest Application
  web-api:
    extends:
      file: docker-services.yml
      service: app
    container_name: kcworks-api
    command: ["uwsgi /opt/invenio/var/instance/uwsgi_rest.ini"]
    image: ${KCWORKS_IMAGE}
    ports:
      - "5001"
    volumes:
      # - static_data:/opt/invenio/var/instance/static
      - archived_data:/opt/invenio/var/instance/archive
      - uploaded_data:/opt/invenio/var/instance/data
      - /${MIGRATION_LOCAL_DATA_DIR}:${MIGRATION_SERVER_DATA_DIR}
  # Worker
  worker:
    extends:
      file: docker-services.yml
      service: app
    container_name: kcworks-worker
    command: ["celery -A invenio_app.celery worker --beat --loglevel INFO"]
    image: ${KCWORKS_IMAGE}
    volumes:
      - uploaded_data:/opt/invenio/var/instance/data
      - archived_data:/opt/invenio/var/instance/archive
    depends_on:
      mq:
        condition: service_started
volumes:
  archived_data:
  static_data:
  uploaded_data:
