common_fields:
  "1":
    - previously_published
    - doi
    - resource_type
    - combined_titles
    - combined_dates
    - abstract
  "2":
    - communities
    - creators
    - contributors
    - ai
    - funding
  "3":
    - subjects
    - keywords
    - content_warning
  "4":
    - alternate_identifiers
    - related_works
  "5":
    - file_upload
    - metadata_only
    - licenses
  "6":
    - admin_metadata
  "7":
    - submission
    - access_rights
    - delete
extras_by_type:
  audiovisual:
    "1":
    "2":
    "3":
      - language
    "4":
    "5":
    "6":
      - admin_metadata
  instructionalResource-syllabus:
    "1":
    "2":
    "3":
      - language
    "4":
    "5":
    "6":
      - admin_metadata
  other:
    "1":
    "2":
    "3":
      - language
    "4":
    "5":
    "6":
  textDocument-book:
    "1":
    "2":
    "3":
      - language
    "4":
      - book_detail
    "5":
    "6":
  textDocument-bookSection:
    "1":
    "2":
    "3":
      - language
    "4":
    "5":
    "6":
  textDocument-journalArticle:
    "1":
    "2":
    "3":
      - language
    "4":
    "5":
    "6":
  textDocument-review:
    "1":
    "2":
    "3":
      - language
    "4":
    "5":
    "6":