common_fields:
  "1":
    - previously_published
    - doi
    - resource_type
    - combined_titles
    - combined_dates
    - abstract
  "2":
    - communities
    - creators
    - contributors
    - ai
    - funding
  "3":
    - language
    - subjects_keywords
    - content_warning
  "4":
    - alternate_identifiers
    - series
    - related_works
  "5":
    - file_upload
    - metadata_only
    - licenses
  "6":
    - admin_metadata
  "7":
    - submit_actions
extras_by_type:
  audiovisual:
  audiovisual-audioRecording:
  audiovisual-documentary:
  audiovisual-interviewRecording:
  audiovisual-musicalRecording:
  audiovisual-other:
  audiovisual-performance:
  audiovisual-podcastEpisode:
  audiovisual-videoRecording:
  dataset:
  image:
  image-chart:
  image-diagram:
  image-figure:
  image-map:
  image-visualArt:
  image-photograph:
  image-other:
  instructionalResource:
  instructionalResource-curriculum:
  instructionalResource-lessonPlan:
  instructionalResource-other:
  instructionalResource-syllabus:
  presentation:
  presentation-conferencePaper:
  presentation-conferencePoster:
  presentation-presentationText:
  presentation-slides:
  presentation-other:
  software:
  software-3DModel:
  software-application:
  software-computationalModel:
  software-computationalNotebook:
  software-service:
  software-other:
  textDocument:
  textDocument-abstract:
  textDocument-bibliography:
  textDocument-blogPost:
  textDocument-book:
    "4":
      - publication_detail
      - book_volume_pages
  textDocument-bookSection:
  textDocument-conferenceProceeding:
  textDocument-dataManagementPlan:
  textDocument-documentation:
  textDocument-editorial:
  textDocument-essay:
  textDocument-interviewTranscript:
  textDocument-journalArticle:
  textDocument-legalComment:
  textDocument-legalResponse:
  textDocument-magazineArticle:
  textDocument-monograph:
  textDocument-newspaperArticle:
  textDocument-onlinePublication:
  textDocument-poeticWork:
  textDocument-preprint:
  textDocument-report:
  textDocument-review:
  textDocument-technicalStandard:
  textDocument-thesis:
  textDocument-whitePaper:
  textDocument-workingPaper:
  textDocument-other:
  other:
  other-catalog:
  other-collection:
  other-event:
  other-interactiveResource:
  other-notes:
  other-patent:
  other-peerReview:
  other-physicalObject:
  other-workflow: